name: pull request

on:
  push:
    branches:
      - dev

jobs:
  pull-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch latest changes from source branch
      run: |
        git checkout test
        git pull origin dev
        git push origin test
