name: pull request

on:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          title: "Feature Completed"
          body: "This pull request is to merge a completed feature from dev to test."

          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        if: success()
  
      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Run Unit Tests
        run: python Test/Test.py

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          title: "Feature Completed"
          body: "This pull request is to merge a completed feature from dev to master."
        if: success()
