name: pull to master

on:
  workflow_run:
    workflows: ["unit test"]
    types:
      - completed

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        title: "Feature Completed"
        body: "This pull request is to merge a completed feature from dev to master."
