name: pull request

on:
  push:
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          title: "Feature Completed"
          body: "This pull request is to merge a completed feature from the dev branch to the test branch. It has taken me an hour to complete this"

      - name: Trigger Unit Test Workflow
        uses: actions/workflow-dispatch@v2
        with:
          workflow: unit_test.yml
          token: ${{ secrets.GITHUB_TOKEN }}
