name: pull request

on:
  push:
    branches:
      - dev

jobs:
  pull-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch latest changes from source branch
      run: |
        git fetch origin dev:dev
        git checkout test
        git merge dev
        git push origin test
